# Number of rows of slots of your server selector menu. For example '2' will mean 2*9 = 18 slots. Max value is 6.
rows: 2

# This will be displayed as the title of the menu. You cannot have multiple menus with the same title!
title: 'Server Selector'

# This will be the name of the server selector item
item-name: 'Server Selector'

# Item lore. For no lore, put 'none' in the first line.
item-lore:
- 'Line 1'
- 'Line 2'

# The name of the server selector item.
item: COMPASS
data: 0

# Give the item when a player joins?
on-join: true

# What slot should the item be in? Specify -1 to automatically put it in the first available slot.
inv-slot: 0

# URL clickable message
url-message: '&3&lClick here'

# Command to open the menu. Specify "none" for no command. (without /)
command: "menu"

# https://github.com/ServerSelectorX/ServerSelectorX/wiki/Free-%7C-Items-in-the-server-selector
menu:

  # Server item
  3:
    ping-server: false
    ip: play.example.com
    port: 1234
    
    action: 'srv:kitpvp'

    # Online is used when ping-server is turned off, or ping-server is turned on and the server is online.
    online:
      item: DIAMOND_SWORD
      name: '&aKitPvP Server'
      lore:
       - 'There are {online} out of {max} players online.'
       - 'Message of the day: {motd}'
      
    # Offline is used when ping-server is turned on and the server is offline.
    offline:
      item: WOODEN_SWORD
      name: '&cKitPvP Server'
      lore:
       - Ipsum lorem
       - Amet sit dolor
       - The server is offline

  # Message item
  5:
    action: 'msg:Hello'
    online:
      item: 'head:auto' # You can use head:auto to get the head of the player opening the menu, or head:SomethingElse to get the head of a specific player.
      name: 'This is you!'
      lore:
       - This item does nothing
  
  # No action item
  -1: # -1 means everything else
    action: 'none'
    online:
      # On 1.13+, remove the data value and use LIGHT_GRAY_STAINED_GLASS_PANE
      item: STAINED_GLASS_PANE
      data: 8
      name: ''
      lore:
